/* dig_sumprod.c */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct {
    long nn;
    long *nvect;
} var= {
    0,
    NULL
};

static void *ecalloc (size_t n, size_t m);

typedef struct NumStat {
    int ndig[10]; /* ndig[0]: not used */
                  /* ndig[1]: not generated by NumSplitter */
    long long n;       /* sum of 'ndig' */
    long long prod;    /* sum of i*ndig[i] */
    long long sum;     /* prod of i^ndig[i] */
} NumStat;

static void NUS_Clear (NumStat *nus);
static void NUS_Print (FILE *f, NumStat *nus);
static void NUS_Calc (NumStat *nus);
static void NUS_Process (NumStat *nus, int i);

typedef struct NumSplitter NumSplitter;

static NumSplitter *NSP_NewMin (int n, int minval);
static inline NumSplitter *NSP_New (int n) {
    return NSP_NewMin (n, 2);
}
static void         NSP_Delete (NumSplitter *nsp);
static int          NSP_Next (NumSplitter *nsp, NumStat *into);

int main (void) {
    for (int i=4; i<=58; ++i) {
        NumSplitter *nsp= NSP_New (i);
        NumStat nus;

/*      printf ("\n=== i=%d ===\n\n", i); */
        while (NSP_Next (nsp, &nus) == 0) {
            NUS_Process (&nus, i);
        }
        NSP_Delete (nsp);
    }

    return 0;
}

static void NUS_Clear (NumStat *nus) {
    memset (nus, 0, sizeof *nus);
    nus->prod= 1;
}

static void NUS_Print (FILE *f, NumStat *nus) {
    for (int i=0; i<=9; ++i) {
        int ndig= nus->ndig[i];
        if (ndig<4) {
            for (int j=0; j<ndig; ++j) fputc ('0'+i, f);
        } else {
            fprintf(f, "%c<%d>", '0'+i, ndig);
        }
    }
}

static void NUS_Calc (NumStat *nus) {
    long long n= 0, sum= 0, prod= 1;
    for (int i=0; i<=9; ++i) {
        int ndig= nus->ndig[i];
        if (ndig) {
            n += ndig;
            sum  += ndig*i;
            for (int j=0; j<ndig; ++j) prod *= i;
        }
    }
    nus->n= n;
    nus->sum= sum;
    nus->prod= prod;
}

static void NUS_Process (NumStat *nus, int i) {
/*  NUS_Print (stdout, nus); */
    NUS_Calc (nus);
/*  fprintf (stdout, " n=%lld, sum=%lld, prod=%lld\n", n, sum, prod);  */

    nus->ndig[1]= nus->prod - nus->sum +1;
    nus->n   += nus->ndig[1];
    nus->sum += nus->ndig[1];
    fprintf (stdout, "%6lld %6lld %6lld  ", nus->n, (long long)i, nus->prod);
    NUS_Print (stdout, nus);
    fputc ('\n', stdout);
}

static void *ecalloc (size_t n, size_t m) {
    void *p= calloc (n, m);
    if (n && m && p==NULL) {
        fprintf (stderr, "Out of memory\n");
        exit (12);
    }
    return p;
}

struct NumSplitter {
    int n;
    int minval; /* default: 2 */

/* split into a pair: possible if 4 <= n <= 18 */
    short eof2;
    int next2; /* first/lesser value of the pair 2..[n/2] */

/* split into 3+ elem: possible if 6 <= n */
    short eofN; /* split into 3+ elem: possible if 6 <= n */
    int nextN;  /* first elem of the 3+ elem */
    NumSplitter *child;
};

static NumSplitter *NSP_NewMin (int n, int minval) {
    NumSplitter *nsp= NULL;
    nsp= ecalloc (n, sizeof *nsp);
    nsp->n= n;
    nsp->minval= minval;

    if (n<2*minval || n>18) {
        nsp->eof2= 1;
    } else {
        nsp->eof2= 0;
        if (n<=minval+9) nsp->next2= minval;
        else             nsp->next2= n/2;
    }

    if (n<3*minval) {
        nsp->eofN= 1;
    } else {
        nsp->eofN= 0;
        nsp->nextN= minval;
    }
    return nsp;
}

static void NSP_Delete (NumSplitter *nsp) {
    NumSplitter *chld;

    if (! nsp) return;
    if ((chld= nsp->child)!=NULL) {
        nsp->child= NULL;
        NSP_Delete (chld);
    }
    free (nsp);
}

static int NSP_Next_N (NumSplitter *nsp, NumStat *into) {
    int found= 0, eof= 0, rc= EOF;

    if (nsp->eofN) return EOF;
    int v1= nsp->nextN;
    int v2= nsp->n - v1;

    while (!found && !eof) {
        if (nsp->child==NULL) {
            if (v2<2*v1) {
                eof= 1;
                continue;
            } else {
                nsp->child= NSP_NewMin (v2, v1);
            }
        }
        rc= NSP_Next (nsp->child, into);
        if (rc==0) {
            into->ndig[v1] += 1;
            into->n    +=  1;
            into->sum  += v1;
            into->prod *= v1;
            found= 1;
            continue;
        }
        v1 += 1;
        v2 -= 1;
        if (v1>9 || v2<2*v1) {
            eof= 1;
            continue;
        }
        nsp->nextN= v1;
        if (nsp->child) {
            NSP_Delete (nsp->child);
            nsp->child= NULL;
        }
    }
    if (eof) {
        nsp->eofN= 1;
        return EOF;
    } else {
        return 0;
    }
}

static int NSP_Next (NumSplitter *nsp, NumStat *into) {
    NUS_Clear (into);
    if (nsp->eof2) return NSP_Next_N (nsp, into);
    int v1= nsp->next2;
    int v2= nsp->n - v1;

    if (v1<2 || v1>9 || v2<v1 || v2>9) {
        nsp->eof2= 1;
        return NSP_Next_N (nsp, into);
    }
    if (v1+1 >= v2) { /* ez a mostani az utolso */
        nsp->eof2= 1;
    } else {               /* meg lesz/lehet kovetkezo */
        nsp->next2 += 1;
    }
    into->ndig[v1] += 1;
    into->ndig[v2] += 1;
    into->n= 2;
    into->sum=  v1+v2;
    into->prod= v1*v2;
    return 0;
}
